-- MySQL Script generated by MySQL Workbench
-- Thu Jun 30 00:10:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema practica_dp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `practica_dp` ;

-- -----------------------------------------------------
-- Schema practica_dp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practica_dp` DEFAULT CHARACTER SET utf8mb4 ;
USE `practica_dp` ;

-- -----------------------------------------------------
-- Table `practica_dp`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_dp`.`addresses` (
  `Id_Distribuidor` VARCHAR(25) NULL DEFAULT NULL,
  `Calle` VARCHAR(255) NULL DEFAULT NULL,
  `Numero_Casa` VARCHAR(25) NULL DEFAULT NULL,
  `Colonia` VARCHAR(120) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `practica_dp`.`distributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_dp`.`distributors` (
  `Id` VARCHAR(11) NOT NULL,
  `Fecha_Registro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `practica_dp`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_dp`.`persons` (
  `Id_Distribuidor` VARCHAR(25) NULL DEFAULT NULL,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  `Apellido_Paterno` VARCHAR(255) NULL DEFAULT NULL,
  `Apellido_Materno` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

USE `practica_dp` ;

-- -----------------------------------------------------
-- procedure GUARDAR_DISTRIBUIDOR
-- -----------------------------------------------------

DELIMITER $$
USE `practica_dp`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GUARDAR_DISTRIBUIDOR`(
	IN `ID_I` VARCHAR(25),
	IN `NOMBRE_I` VARCHAR(120),
	IN `APELLIDOP_I` VARCHAR(120),
	IN `APELLIDOM_I` VARCHAR(120),
	IN `CALLE_I` VARCHAR(120),
	IN `NUMERO_I` VARCHAR(120),
	IN `COLONIA_I` VARCHAR(120))
BEGIN

	-- 1. Guarda un registro y guarda cambios
	DECLARE hasError BOOLEAN DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR sqlexception SET hasError = 1;
	

			
			START TRANSACTION;
			
				INSERT INTO distributors 
					(
						Id,
						Fecha_Registro
					) 
					VALUES 
					(
						ID_I,
						NOW()
					);
					
				INSERT INTO persons 
				(
					Id_Distribuidor,
					Nombre,
					Apellido_Paterno,
					Apellido_Materno
				) 
				VALUES 
				(
					ID_I,
					NOMBRE_I,
					APELLIDOP_I, 
					APELLIDOM_I
				);
					
				INSERT INTO addresses 
				(
					Id_Distribuidor,
					Calle,
					Numero_Casa,
					Colonia
				) 
				VALUES 
				(
					ID_I,
					CALLE_I,
					NUMERO_I, 
					COLONIA_I
				);
					
			IF hasError THEN
		
				ROLLBACK;
				SELECT 'error';
				
			ELSE
		 
				COMMIT;
				
			END IF;
			


END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_ConsultarDatosEspecificos
-- -----------------------------------------------------

DELIMITER $$
USE `practica_dp`$$
CREATE DEFINER=`` PROCEDURE `SP_ConsultarDatosEspecificos`(IN `ID_I` VARCHAR(25))
BEGIN
SELECT concat (p.Nombre," ", p.Apellido_Paterno) As Nombre_Completo, d.Calle,d.Numero_casa,d.Colonia from persons p inner join addresses d on d.Id_Distribuidor = p.ID_Distribuidor where p.ID_Distribuidor = `ID_I`;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_ConsultarTodosDatos
-- -----------------------------------------------------

DELIMITER $$
USE `practica_dp`$$
CREATE DEFINER=`` PROCEDURE `SP_ConsultarTodosDatos`()
BEGIN
SELECT concat (p.Nombre," ", p.Apellido_Paterno) As Nombre_Completo, d.Calle,d.Numero_casa,d.Colonia from persons p inner join addresses d on d.Id_Distribuidor = p.ID_Distribuidor;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
